language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script: DATABASE_URL='fake' py.test package_monitor/ --doctest-modules